### ISSUE TITLE
Only digits allowed for len(password) >= 10?

### ISSUE THREAD

**Issue by supervirus** [CheckiO-Missions/checkio-mission-acceptable-password-4#4]
In the password check rules is stated:
> should contain at least one digit, but it cannot consist of just digits;

But this is checked:
`is_acceptable_password('12345678910') == True`

In my unterstanding a password containing only digits is not ok, even if its longer then 10.

**Comment by oduvan** [comment]
fixed. will be synced soon.

Thank you
